// Definições das 33 pedras místicas com suas propriedades exatas da tabela
export const stonePrompts = {
  ametista: {
    name: "Ametista",
    color: "#9966CC",
    meaning: "Espiritualidade, calma, proteção",
    description: "Drusa bruta roxa com cristais pontiagudos",
    origin: "Brasil, Uruguai, Zâmbia",
    texture: "crystalline",
    shape: "hexagonal",
    finish: "raw",
    energyLevel: 85,
  },
  quartzoRosa: {
    name: "Quartzo Rosa",
    color: "#F4C2C2",
    meaning: "Amor próprio, harmonia, cura emocional",
    description: "Pedra polida arredondada, rosa suave",
    origin: "Brasil, Madagascar, EUA",
    texture: "smooth",
    shape: "oval",
    finish: "polished",
    energyLevel: 78,
  },
  quartzoTransparente: {
    name: "Quartzo Transparente",
    color: "#F5F5F5",
    meaning: "Harmonia, clareza, amplificação de energia",
    description: "Cristal bruto transparente, formato hexagonal",
    origin: "Brasil, China, EUA",
    texture: "crystalline",
    shape: "hexagonal",
    finish: "raw",
    energyLevel: 90,
  },
  turquesa: {
    name: "Turquesa",
    color: "#40E0D0",
    meaning: "Criatividade, comunicação, proteção",
    description: "Bloco polido azul-turquesa com veios",
    origin: "Irã, EUA, México",
    texture: "veined",
    shape: "block",
    finish: "polished",
    energyLevel: 82,
  },
  agataNegra: {
    name: "Ágata Negra",
    color: "#0D0D0D",
    meaning: "Equilíbrio, proteção energética",
    description: "Fatia polida preta brilhante",
    origin: "Brasil, Índia, Austrália",
    texture: "banded",
    shape: "slice",
    finish: "polished",
    energyLevel: 75,
  },
  agataDeFogo: {
    name: "Ágata de Fogo",
    color: "#B22222",
    meaning: "Vitalidade, coragem, proteção",
    description: "Pedra polida com tons quentes e brilho",
    origin: "México, Brasil, EUA",
    texture: "banded",
    shape: "irregular",
    finish: "polished",
    energyLevel: 88,
  },
  olhoDeTigre: {
    name: "Olho de Tigre",
    color: "#B8860B",
    meaning: "Coragem, confiança, afastar inveja",
    description: "Cabochão polido com listras douradas",
    origin: "África do Sul, Austrália, Índia",
    texture: "chatoyant",
    shape: "cabochon",
    finish: "polished",
    energyLevel: 80,
  },
  lapisLazuli: {
    name: "Lápis-Lazúli",
    color: "#26619C",
    meaning: "Verdade, sabedoria, conexão espiritual",
    description: "Bloco bruto azul com manchas douradas",
    origin: "Afeganistão, Chile, Rússia",
    texture: "speckled",
    shape: "block",
    finish: "raw",
    energyLevel: 86,
  },
  jade: {
    name: "Jade",
    color: "#00A86B",
    meaning: "Pureza, calma, prosperidade",
    description: "Escultura polida verde brilhante",
    origin: "China, Mianmar, Guatemala",
    texture: "smooth",
    shape: "heart",
    finish: "polished",
    energyLevel: 84,
  },
  pirita: {
    name: "Pirita",
    color: "#CFB53B",
    meaning: "Prosperidade, proteção, riqueza",
    description: "Cubo bruto dourado metálico",
    origin: "Espanha, Peru, Rússia",
    texture: "metallic",
    shape: "cubic",
    finish: "raw",
    energyLevel: 79,
  },
  onix: {
    name: "Ônix",
    color: "#0A0A0A",
    meaning: "Clareza mental, transformação de energia",
    description: "Esfera polida preta brilhante",
    origin: "Brasil, México, Índia",
    texture: "smooth",
    shape: "sphere",
    finish: "polished",
    energyLevel: 77,
  },
  amazonita: {
    name: "Amazonita",
    color: "#7FFFD4",
    meaning: "Boa sorte, equilíbrio, harmonia",
    description: "Pedra polida verde-azulada",
    origin: "Brasil, Madagascar, EUA",
    texture: "smooth",
    shape: "irregular",
    finish: "polished",
    energyLevel: 81,
  },
  citrino: {
    name: "Citrino",
    color: "#E4D00A",
    meaning: "Sucesso, prosperidade, energia positiva",
    description: "Cristal bruto amarelo translúcido",
    origin: "Brasil, Rússia, Madagascar",
    texture: "crystalline",
    shape: "pointed",
    finish: "raw",
    energyLevel: 87,
  },
  turmalinaNegra: {
    name: "Turmalina Negra",
    color: "#2C3539",
    meaning: "Proteção, ancoramento, bloqueio de energias",
    description: "Bastão bruto preto fosco",
    origin: "Brasil, África, EUA",
    texture: "striated",
    shape: "rod",
    finish: "raw",
    energyLevel: 92,
  },
  pedraDaLua: {
    name: "Pedra da Lua",
    color: "#F5F5F5",
    meaning: "Intuição, energia feminina, dons psíquicos",
    description: "Cabochão polido branco leitoso com brilho",
    origin: "Índia, Sri Lanka, Austrália",
    texture: "adularescent",
    shape: "cabochon",
    finish: "polished",
    energyLevel: 89,
  },
  pedraDoSol: {
    name: "Pedra do Sol",
    color: "#E67E22",
    meaning: "Vitalidade, sorte, alegria",
    description: "Pedra polida laranja brilhante",
    origin: "Índia, Canadá, Noruega",
    texture: "aventurescent",
    shape: "irregular",
    finish: "polished",
    energyLevel: 83,
  },
  quartzoAzul: {
    name: "Quartzo Azul",
    color: "#ADD8E6",
    meaning: "Cura emocional, calma, meditação",
    description: "Cristal bruto azul claro",
    origin: "Brasil, Áustria, China",
    texture: "crystalline",
    shape: "pointed",
    finish: "raw",
    energyLevel: 80,
  },
  aguaMarinha: {
    name: "Água-Marinha",
    color: "#B0E0E6",
    meaning: "Paz, comunicação espiritual, clareza",
    description: "Facetada azul clara, formato gota",
    origin: "Brasil, Paquistão, Madagascar",
    texture: "transparent",
    shape: "faceted",
    finish: "cut",
    energyLevel: 82,
  },
  cianitaAzul: {
    name: "Cianita Azul",
    color: "#4682B4",
    meaning: "Proteção, conexão espiritual, alinhamento",
    description: "Lâmina bruta azul com textura fibrosa",
    origin: "Brasil, Suíça, Nepal",
    texture: "bladed",
    shape: "blade",
    finish: "raw",
    energyLevel: 85,
  },
  fluorita: {
    name: "Fluorita",
    color: "#9966CC",
    meaning: "Clareza mental, purificação, sucesso",
    description: "Cubo polido multicolor (verde, roxo)",
    origin: "China, México, África do Sul",
    texture: "banded",
    shape: "cubic",
    finish: "polished",
    energyLevel: 84,
  },
  obsidiana: {
    name: "Obsidiana",
    color: "#2E1E21",
    meaning: "Proteção contra inveja, conexão espiritual",
    description: "Fragmento bruto preto brilhante",
    origin: "México, Islândia, EUA",
    texture: "glassy",
    shape: "irregular",
    finish: "raw",
    energyLevel: 76,
  },
  calcita: {
    name: "Calcita",
    color: "#FFA500",
    meaning: "Purificação, equilíbrio, meditação",
    description: "Bloco bruto laranja translúcido",
    origin: "México, Brasil, Islândia",
    texture: "crystalline",
    shape: "rhombohedral",
    finish: "raw",
    energyLevel: 78,
  },
  cornalina: {
    name: "Cornalina",
    color: "#B31B1B",
    meaning: "Vitalidade, coragem, criatividade",
    description: "Pedra polida laranja vibrante",
    origin: "Brasil, Índia, Uruguai",
    texture: "translucent",
    shape: "rounded",
    finish: "polished",
    energyLevel: 82,
  },
  labradorita: {
    name: "Labradorita",
    color: "#6C7A89",
    meaning: "Intuição, proteção, transformação",
    description: "Placa polida com reflexos coloridos",
    origin: "Canadá, Madagascar, Finlândia",
    texture: "labradorescent",
    shape: "slab",
    finish: "polished",
    energyLevel: 88,
  },
  jaspeVermelho: {
    name: "Jaspe Vermelho",
    color: "#B22222",
    meaning: "Força, estabilidade, energia vital",
    description: "Esfera polida vermelha opaca",
    origin: "África do Sul, Brasil, Índia",
    texture: "opaque",
    shape: "sphere",
    finish: "polished",
    energyLevel: 79,
  },
  rodonita: {
    name: "Rodonita",
    color: "#E77471",
    meaning: "Cura emocional, compaixão, amor",
    description: "Pedra polida rosa com veios pretos",
    origin: "Austrália, Rússia, Peru",
    texture: "mottled",
    shape: "irregular",
    finish: "polished",
    energyLevel: 77,
  },
  howlita: {
    name: "Howlita",
    color: "#F5F5F5",
    meaning: "Calma, paciência, redução de estresse",
    description: "Bloco polido branco com veios cinza",
    origin: "Canadá, EUA, México",
    texture: "veined",
    shape: "nodular",
    finish: "polished",
    energyLevel: 75,
  },
  aventurina: {
    name: "Aventurina",
    color: "#3CB371",
    meaning: "Sorte, prosperidade, equilíbrio",
    description: "Cabochão polido verde brilhante",
    origin: "Brasil, Índia, Rússia",
    texture: "aventurescent",
    shape: "cabochon",
    finish: "polished",
    energyLevel: 80,
  },
  agataMusgo: {
    name: "Ágata Musgo",
    color: "#D0F0C0",
    meaning: "Conexão com a natureza, equilíbrio",
    description: "Fatia polida com inclusões verdes",
    origin: "Índia, Austrália, EUA",
    texture: "dendritic",
    shape: "slice",
    finish: "polished",
    energyLevel: 81,
  },
  topazio: {
    name: "Topázio",
    color: "#0D98BA",
    meaning: "Clareza, alegria, proteção",
    description: "Gema facetada azul brilhante",
    origin: "Brasil, Paquistão, Rússia",
    texture: "transparent",
    shape: "faceted",
    finish: "cut",
    energyLevel: 83,
  },
  granada: {
    name: "Granada",
    color: "#7B1113",
    meaning: "Paixão, energia vital, regeneração",
    description: "Cristal bruto vermelho escuro",
    origin: "Índia, Brasil, África do Sul",
    texture: "vitreous",
    shape: "dodecahedral",
    finish: "raw",
    energyLevel: 86,
  },
  cristalDeMorango: {
    name: "Cristal de Morango",
    color: "#FF69B4",
    meaning: "Amor, harmonia, energia suave",
    description: "Pedra polida rosa com inclusões",
    origin: "México, Rússia, Brasil",
    texture: "included",
    shape: "irregular",
    finish: "polished",
    energyLevel: 79,
  },
  obsidianaFlocoDeNeve: {
    name: "Obsidiana Floco de Neve",
    color: "#2F4F4F",
    meaning: "Equilíbrio, proteção, purificação",
    description: "Pedra polida preta com manchas brancas",
    origin: "EUA, México, Islândia",
    texture: "snowflake",
    shape: "irregular",
    finish: "polished",
    energyLevel: 82,
  },
}

// Função para gerar um prompt com base em múltiplos tipos de pedras
export const getMultiStonePrompt = (stoneTypes: string[]): string => {
  if (!stoneTypes || stoneTypes.length === 0) {
    return "Considere que a pessoa que abriu a CAIXA está buscando compreender seu Estado de Consciência Interna (ECI). Baseando-se unicamente na disposição das pedras místicas, desenvolva uma leitura inédita, dividida em três partes: (1) percepção interior atual, (2) bloqueios energéticos ocultos e (3) caminhos para expansão do ECI. Utilize linguagem simbólica, espiritual e poética, sem repetir nenhuma estrutura ou frase de leituras anteriores. Essa leitura deve ser única, como um oráculo vivo. Inicie com um chamado ao espírito da caixa e conclua com uma pergunta de reflexão para o consulente."
  }

  const stoneDetails = stoneTypes.map((type) => {
    const stone = stonePrompts[type as keyof typeof stonePrompts]
    return stone ? `${stone.name} (significado: ${stone.meaning})` : "Pedra desconhecida"
  })

  return `Considere que a pessoa que abriu a CAIXA está buscando compreender seu Estado de Consciência Interna (ECI). 
Baseando-se na disposição das seguintes pedras místicas: ${stoneDetails.join(", ")}.
Desenvolva uma leitura inédita, dividida em três partes: 
(1) percepção interior atual, 
(2) bloqueios energéticos ocultos e 
(3) caminhos para expansão do ECI. 

Utilize linguagem simbólica, espiritual e poética, sem repetir nenhuma estrutura ou frase de leituras anteriores. 
Essa leitura deve ser única, como um oráculo vivo. 
Inicie com um chamado ao espírito da caixa e conclua com uma pergunta de reflexão para o consulente.`
}
